---
# SPDX-FileCopyrightText: 2023 Stoney Jackson <dr.stoney@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

image: gitpod/workspace-full:latest

tasks:
  - name: Install PLCC
    command: |
        sdk install java < /dev/null
        /bin/bash -c "$(curl -fsSL https://github.com/ourPLCC/plcc/raw/main/installers/plcc/install.bash)" >> ~/.bashrc
        exec bash
