---
# SPDX-FileCopyrightText: 2023 Stoney Jackson <dr.stoney@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

image: gitpod/workspace-full:2023-08-09-14-26-44

tasks:
  - name: Install JDK
    command: sdk install java 21-open < /dev/null

  - name: Install PLCC
    command: ./.gitpod/install-plcc.sh
